[package]
name = "rs-builder"
version = "0.1.0"
edition = "2018"
authors = ["Xu Shaohua <shaohua@biofan.org"]
readme = "README.md"
license = "GPL-3.0"

[dependencies]
clap = "2.33.3"
env_logger = "0.8.3"
glob = "0.3.0"
log = "0.4.14"
serde = "1.0.125"
serde_derive = "1.0.125"
toml = "0.5.8"
