[package]
name = "pifu"
version = "0.3.3"
edition = "2021"
authors = ["Xu Shaohua <shaohua@biofan.org"]
repository = "https://github.com/PifuProject/pifu"
readme = "README.md"
license = "GPL-3.0"
description = "Cross platform package build tool"
categories = [
  "development-tools::build-utils"
]
keywords = [
  "build tools",
  "packaging",
]

[dependencies]
ar = "0.9.0"
chrono = "0.4.19"
clap = "3.1.18"
colored = "2.0.0"
directories = "4.0.1"
env_logger = "0.9.0"
flate2 = "1.0.24"
fs_extra = "1.2.0"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
md5 = "0.7.0"
num_cpus = "1.13.1"
regex = "1.5.6"
reqwest = { version = "0.11.10", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
sha2 = "0.10.2"
tar = "0.4.38"
toml = "0.5.9"
walkdir = "2.3.2"
xz2 = "0.1.7"

[profile.release]
lto = true
opt-level = 3
debug = false

[features]
