[package]
name = "rs-builder"
version = "0.1.0"
edition = "2018"
authors = ["Xu Shaohua <shaohua@biofan.org"]
readme = "README.md"
license = "GPL-3.0"

[dependencies]
clap = "2.33.3"
env_logger = "0.8.3"
flate2 = "1.0.20"
glob = "0.3.0"
log = "0.4.14"
md5 = "0.7.0"
num_cpus = "1.13.0"
serde = "1.0.125"
serde_derive = "1.0.125"
tar = "0.4.33"
toml = "0.5.8"
walkdir = "2.3.2"
xz2 = "0.1.6"

[profile.release]
lto = true
opt-level = 3
debug = false
