[package]
name = "pifu"
version = "0.2.4"
edition = "2018"
authors = ["Xu Shaohua <shaohua@biofan.org"]
repository = "https://github.com/PifuProject/pifu"
readme = "README.md"
license = "GPL-3.0"
description = "Cross platform package build tool"
categories = ["development-tools::build-utils"]

[dependencies]
ar = "0.8.0"
chrono = "0.4.19"
clap = "2.33.3"
directories = "3.0.2"
env_logger = "0.9.0"
flate2 = "1.0.20"
fs_extra = "1.2.0"
glob = "0.3.0"
log = "0.4.14"
md5 = "0.7.0"
num_cpus = "1.13.0"
regex = "1.5.4"
serde = "1.0.127"
serde_derive = "1.0.127"
serde_json = "1.0.66"
tar = "0.4.37"
toml = "0.5.8"
walkdir = "2.3.2"
xz2 = "0.1.6"

[profile.release]
lto = true
opt-level = 3
debug = false
