
[metadata]
name = "pifu-hello"
product_name = "Pifu Example"
app_id = "org.biofan.hello"
author = "Xu Shaohua <shaohua@biofan.org"
copyright = "Copyright (c) Xu Shaohua"
description = "Rust hello app"
homepage = "https://biofan.org"
version = "1.0.0"
build_id = "2"
license = "GPL-3.0"

workdir = "target/pifu"
src_dir = "."

[linux]
targets = []
arch = ["x86-64"]

files = [
	{from = "target/debug/examples/hello", to = "usr/bin/pifu-hello"},
	{from = "examples/hello.png", to = "usr/share/icons/hicolor/128x128/apps/pifu-hello.png"},
	{from = "examples/hello.desktop", to = "usr/share/applications/pifu-hello.desktop"},
]

[linux.deb]

[windows]
targets = ["nsis"]

files = [
	{from = "target/x86_64-pc-windows-gnu/debug/examples/hello.exe", to="pifu-hello.exe"},
	{from = "examples/hello.png", to = "pifu-hello.png"},
]

[windows.nsis]
one_click = false
per_machine = false
installer_icon = "examples/install.ico"
uninstaller_icon = "examples/uninstall.ico"
