
[metadata]
name = "pifu-hello"
product_name = "Pifu Example"
app_id = "org.biofan.hello"
author = "Xu Shaohua <shaohua@biofan.org"
copyright = "Copyright (c) Xu Shaohua"
description = "Rust hello app"
homepage = "https://biofan.org"
company = "Foo Corporation"
version = "1.0.0"
build_id = "${date}"
license = "GPL-3.0"
license_file = "LICENSE"

workdir = "target/pifu"
src_dir = "."

[linux]
targets = ["app_image"]
arch = ["x86-64"]

files = [
	{from = "target/debug/examples/hello", to = "usr/bin/pifu-hello"},
	{from = "examples/hello.png", to = "usr/share/icons/hicolor/128x128/apps/pifu-hello.png"},
	{from = "examples/hello.desktop", to = "usr/share/applications/pifu-hello.desktop"},
]

[linux.deb]

[linux.app_image]
exe_files = ["target/debug/examples/hello"]

files = [
	{from = "target/debug/examples/hello", to = "pifu-hello"},
	{from = "examples/hello.png", to = "pifu-hello.png"},
	{from = "examples/hello.desktop", to = "pifu-hello.desktop"},
	{from = "examples/AppRun", to = "AppRun"},
]

[windows]
targets = []

exe_file = "pifu-hello.exe"

files = [
	{from = "target/x86_64-pc-windows-gnu/debug/examples/hello.exe", to="pifu-hello.exe"},
	{from = "examples/hello.png", to = "pifu-hello.png"},
	{from = "LICENSE", to = "LICENSE.txt"},
]

[windows.nsis]
#script = "target/pifu/nsis/app.nsi"
include = "examples/empty-script.nsi"
one_click = false
per_machine = false
installer_icon = "examples/install.ico"
uninstaller_icon = "examples/uninstall.ico"
installer_header_icon = "examples/header.bmp"
installer_sidebar = "examples/welcome.bmp"
uninstaller_sidebar = "examples/unwelcome.bmp"
run_on_startup = true
