
[metadata]
name = "qrbox"
app_id = "org.biofan.qrbox"
author = "Xu Shaohua <shaohua@biofan.org"
description = "QR generator"
version = "1.0.0"
license = "GPL-3.0"

workdir = "target/rs-builder"
assets = [
	{from = "target/release/qrbox", to = "bin/qrbox"},
]


[linux]
targets = ["deb"]
arch = ["x86-64"]
artifact_name = "${name}-${version}.${ext}"

[linux.deb]
